require('user.config.tools.diagnostic')
vim.defer_fn(function ()
    require('user.config.tools.goto_preview')
    require('user.config.tools.formatter')
    require('user.config.tools.luasnip')
    require('user.config.tools.lspkind')
    require('user.config.tools.navic')
end, 200)

vim.defer_fn(function()
    require('user.config.tools.autopairs.autopairs')
end, 300)
